# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[tool.poetry]
name = "nvmesh-utils"
version = "3.5.0"
description = "NVMesh SDK, CLI tools and diagnostics"
authors = ["NVMesh Team <nvmesh-dev@nvidia.com>"]
readme = "README.md"
packages = [{include = "xlro"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
confetti = "^2.5.3"
click = "7.1.2"
click-shell = "^2.1"
concurrent-log-handler = "^0.9.25"
dateparser = "^1.1.7"
deprecated = "^1.2.13"
future = "^0.18.3"
jinja2 = "^3.1.5"
packaging = "^24.0"
paramiko = "^3.0.0"
pathlib2 = "^2.3.7.post1"
psutil = "^5.9.4"
pytz = "^2022.7.1"
requests = "^2.33.1"
humanfriendly = "^10.0"
pyyaml = "^6.0"
configparser = "^5.3.0"
pyjsparser = "^2.7.1"
urllib3 = "^2.7.0"
setuptools = "80.10.2"
cryptography = "^49.0.0"
cffi = ">=2"
gnureadline = "8.1.2"

[tool.poetry.group.build.dependencies]
pyinstaller = "^6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
